version: '3.3'
services:
        torchlm:
          build:
            context: ./
            args:
              USER_ID: ${USERID}
              GROUP_ID: ${GROUPID}
              USER_NAME: ${USERNAME}
          image: "torchlm"
          container_name: "torchlm_cont" 
          network_mode: "host"
          volumes:
            - "${PWD}:/${PWD}"
            #- "/home/${USERNAME}/torch:/home/${USERNAME}/torch"
            - "/dev/:/dev/"
            - "/tmp/.X11-unix:/tmp/.X11-unix"
            - "/dev/snd:/dev/snd"
            - "$HOME/.Xauthority:/$HOME/.Xauthority:rw"
            - "/home/${USERNAME}/.ssh/:/home/${USERNAME}/.ssh/"
          environment:
            - "DISPLAY"
          device_cgroup_rules:
            - "c 81:* rmw"
            - "c 189:* rmw"
          deploy:
            resources:
              reservations:
                devices:
                  - driver: nvidia
                    #device_ids: ['1','2']
                    capabilities: [gpu]
          stdin_open: true
          tty: true